/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-27 16:04:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Worklogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.huatai.biz.impl.ResumeBizImpl;
import com.huatai.util.CommonUtils;
import com.huatai.biz.ResumeBiz;
import com.huatai.entity.*;
import org.apache.commons.fileupload.*;
import org.apache.commons.fileupload.servlet.*;
import java.util.*;
import java.io.*;
import org.apache.commons.fileupload.disk.*;
import java.util.Date;
import java.util.*;

public final class do_005fUpdateInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.apache.commons.fileupload");
    _jspx_imports_packages.add("com.huatai.entity");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.apache.commons.fileupload.servlet");
    _jspx_imports_packages.add("org.apache.commons.fileupload.disk");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.huatai.biz.impl.ResumeBizImpl");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.huatai.util.CommonUtils");
    _jspx_imports_classes.add("com.huatai.biz.ResumeBiz");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	//获得简历信息;
	String userid = request.getParameter("userid");
	//根据userid查询改简历信息是否已存在,以此判断是否可以完善
	ResumeBiz resumnebiz = new ResumeBizImpl();
	Resume resume = resumnebiz.isExit(userid);
	if (resume != null) {
		if (userid.equals(resume.getUserresid())) {
			request.setAttribute("resumemsg", "简历已经存在,无须创建");
			request.getRequestDispatcher("UpdateInfo.jsp").forward(request, response);
		}
	} else {
		//System.out.println("userid==" + userid);
		String resid = CommonUtils.getUUid();
		String restitle = request.getParameter("restitle");
		String resname = request.getParameter("resname");
		String resnumber = request.getParameter("resnumber");

		int reslevel = Integer.parseInt(request.getParameter("reslevel"));
		String level = "";
		if (1 == reslevel) {
			level = "初中";
		} else if (2 == reslevel) {
			level = "高中";
		} else if (3 == reslevel) {
			level = "本科";
			//System.out.println("reslevel==" + level);
		} else if (4 == reslevel) {
			level = "研究生";
		} else if (5 == reslevel) {
			level = "博士";
		}

		String respicpath = request.getParameter("file");
		int resmoney = Integer.parseInt(request.getParameter("resmoney"));
		String money = "";
		if (1 == resmoney) {
			money = "2000以下";
		} else if (2 == resmoney) {
			money = "2000~4000";
		} else if (3 == resmoney) {
			money = "4000~6000";
			//System.out.println("reslevel==" + level);
		} else if (4 == resmoney) {
			money = "6000~8000";
		} else if (5 == resmoney) {
			money = "8000~10000";
		} else if (6 == resmoney) {
			money = "10K以上";
		}
		String resinterest = request.getParameter("resinterest");
		String restimate = request.getParameter("restimate");

		//System.out.println("resmoney=="+resmoney);

		Resume resum = new Resume(resid, restitle, resname, resnumber, level, respicpath, resinterest, money,
				restimate, userid);
		//添加个人简历
		ResumeBiz biz = new ResumeBizImpl();
		boolean isSuccess = biz.insertResume(resum);
		if (isSuccess) {
			//List<Resume> resumelist = biz.getAllResume();
			//session.setAttribute("resumelist", resumelist);
			response.sendRedirect("LookInfo.jsp");
		} else {
			response.getWriter().println("<script type='text/javascript'>alert('简历信息完善失败！');</script>");
		}
	}

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
