/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-21 08:49:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Worklogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.huatai.biz.impl.UserBizImpl;
import com.huatai.biz.UserBiz;
import com.huatai.entity.*;
import org.apache.commons.fileupload.*;
import org.apache.commons.fileupload.servlet.*;
import java.util.*;
import java.io.*;
import org.apache.commons.fileupload.disk.*;
import java.util.Date;
import java.util.*;

public final class workloginsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.apache.commons.fileupload");
    _jspx_imports_packages.add("com.huatai.entity");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.apache.commons.fileupload.servlet");
    _jspx_imports_packages.add("org.apache.commons.fileupload.disk");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.huatai.biz.impl.UserBizImpl");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.huatai.biz.UserBiz");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- 浏览器兼容性设置-->\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- 视图兼容设置 -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<!-- 页面默认使用极速核 -->\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/Hrlogin/pintuer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/Hrlogin/admin.css\">\r\n");
      out.write("<script src=\"../js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".leftnav h2\").click(function() {\r\n");
      out.write("\t\t\t$(this).next().slideToggle(200).next(\"ul\").slideDown(200);\r\n");
      out.write("\t\t\t$(this).siblings().next(\"ul\").slideUp(200);\r\n");
      out.write("\t\t\t//$(this).toggleClass(\"on\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".leftnav ul li a\").click(function() {\r\n");
      out.write("\t\t\t$(\"#a_leader_txt\").text($(this).text());\r\n");
      out.write("\t\t\t$(\".leftnav ul li a\").removeClass(\"on\");\r\n");
      out.write("\t\t\t$(this).addClass(\"on\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f2f9fd;\">\r\n");
      out.write("\t<div class=\"header bg-main\">\r\n");
      out.write("\t\t<div class=\"logo margin-big-left fadein-top\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<img src=\"../images/y.jpg\" class=\"radius-circle rotate-hover\"\r\n");
      out.write("\t\t\t\t\theight=\"50\" alt=\"\" />管理中心\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"head-l\">\r\n");
      out.write("\t\t\t");

				String user = (String) request.getSession().getAttribute("workuser");
			
      out.write("\r\n");
      out.write("\t\t\t<a class=\"button button-little bg-blue\"> <span class=\"icon-login\"></span>\r\n");
      out.write("\t\t\t\t个人：");
      out.print(user);
      out.write("\r\n");
      out.write("\t\t\t</a> &nbsp;&nbsp; <a class=\"button button-little bg-green\"\r\n");
      out.write("\t\t\t\thref=\"workloginsuccess.jsp\"> <span class=\"icon-home\"></span>\r\n");
      out.write("\t\t\t\t后台首页\r\n");
      out.write("\t\t\t</a> &nbsp;&nbsp; <a class=\"button button-little bg-red\"\r\n");
      out.write("\t\t\t\thref=\"../index.jsp\"> <span class=\"icon-power-off\"></span> 退出登录\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		//查询出登录用户的id,以便后面查询对应简历等
		UserBiz userbiz = new UserBizImpl();
		UserInfo userid = userbiz.getUserid(user);
		//System.out.println(userid.getUserid());
		String Url = "UpdateInfo.jsp?userid=" + userid.getUserid();
		String LookUrl = "LookInfo.jsp?userid=" + userid.getUserid();
	
      out.write("\r\n");
      out.write("\t<div class=\"leftnav\">\r\n");
      out.write("\t\t<div class=\"leftnav-title\">\r\n");
      out.write("\t\t\t<strong><span class=\"icon-list\"></span>菜单列表</strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-pencil-square-o\"></span>求职信息管理\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul style=\"display: block\">\r\n");
      out.write("\t\t\t<li><a href=\"LookJob.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>查看招聘信息</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"LookRecord.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>查看投递记录</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-pencil-square-o\"></span>简历信息管理\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(Url);
      out.write("\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>简历信息完善</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-user\"></span>个人信息管理\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(LookUrl);
      out.write("\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>预览简历</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"UpdatePwd.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>修改密码</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<ul class=\"bread\">\r\n");
      out.write("\t\t<li><a href=\"../HrLoginPage/rightmessage.jsp\" target=\"right\"\r\n");
      out.write("\t\t\tclass=\"icon-home\"> 首页</a></li>\r\n");
      out.write("\t\t<li><a href=\"##\" id=\"a_leader_txt\">网站信息</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div class=\"admin\">\r\n");
      out.write("\t\t<iframe scrolling=\"auto\" rameborder=\"0\"\r\n");
      out.write("\t\t\tsrc=\"../HrLoginPage/rightmessage.jsp\" name=\"right\" width=\"100%\"\r\n");
      out.write("\t\t\theight=\"100%\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"text-align: center;\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
