/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-26 09:33:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.HrLoginPage.new_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.huatai.dao.TopicsDao;
import com.huatai.dao.impl.TopicsDaoImpl;
import com.huatai.entity.Topic;
import com.huatai.entity.*;
import java.util.*;

public final class news_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.huatai.entity");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.huatai.dao.impl.TopicsDaoImpl");
    _jspx_imports_classes.add("com.huatai.dao.TopicsDao");
    _jspx_imports_classes.add("com.huatai.entity.Topic");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../css/Hrlogin/pintuer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../css/Hrlogin/admin.css\">\r\n");
      out.write("<script src=\"../../js/jquery.js\"></script>\r\n");
      out.write("<!-- 输入合法性的验证 -->\r\n");
      out.write("<script src=\"../../js/pintuer.js\"></script>\r\n");
      out.write("<script src=\"../../js/img.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction callBack1(code, path, msg) {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"input[name=file]\").val(path);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#dressPic\").attr(\"src\", \"/upload/\" + path);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#dressPic\").show();\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#dressPic\").on(\"load\", function() {\r\n");
      out.write("\t\t\tresizeImg(150, 90, \"dressPic\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"panel admin-panel\">\r\n");
      out.write("\t\t<div class=\"panel-head\" id=\"add\">\r\n");
      out.write("\t\t\t<strong><span class=\"icon-pencil-square-o\"></span>增加内容</strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");

			//从request域获取News实例
			News news = (News) request.getSession().getAttribute("news");
			//System.out.println("news = " + news.getTopic());
			String tid = news.getTopic().getTid();
			//System.out.println("tid = " + tid);

			boolean istrue = "1".equals(tid.trim());
			//System.out.println("istrue = " + istrue);

			TopicsDao topicsDao = new TopicsDaoImpl();
			List<Topic> topicList = topicsDao.getAllTopics();
		
      out.write("\r\n");
      out.write("\t\t<div class=\"body-content\">\r\n");
      out.write("\t\t\t<form method=\"get\" enctype=\"multipart/form-data\"\r\n");
      out.write("\t\t\t\taction=\"do_news_edit.jsp\" class=\"form-x\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"nid\" value=\"");
      out.print(news.getNid());
      out.write("\" />\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t<label>类别：</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"ntid\" style=\"width: 150px\" class=\"input w50\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"-1\">请选择新闻类别</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (Topic topic : topicList) {
									if (tid != null && tid.equals(topic.getTid())) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value='");
      out.print(topic.getTid());
      out.write("' selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(topic.getTname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value='");
      out.print(topic.getTid());
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(topic.getTname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tips\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t<label>标题：</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"input w50\" value=\"");
      out.print(news.getNtitle());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"ntitle\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tips\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t<label>作者：</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"input w50\" name=\"nauthor\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(news.getNauthor());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tips\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t<label>摘要：</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"input\" name=\"nsummary\" style=\"height: 90px;\">");
      out.print(news.getNsummary());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tips\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t<label>内容：</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"ncontent\" class=\"input\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 200px; border: 1px solid #ddd;\">");
      out.print(news.getNcontent());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tips\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t<label>图片：</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t<iframe\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/inc/upload.jsp?callBack=callBack1\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 0px; height: 30px;\" scrolling=\"no\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"url1\" name=\"file\" class=\"input tips\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 20%; float: left;\" value=\"");
      out.print(news.getNpicpath());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<img id=\"dressPic\" src=\"/upload/");
      out.print(news.getNpicpath());
      out.write("\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t width=\"150\" height=\"90\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							String picPath = news.getNpicpath();
							picPath = picPath == null || "NULL".equals(picPath) ? "" : picPath;
							//System.out.println("上传图片~~" + picPath);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(picPath);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t<label></label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"action\" type=\"hidden\" value=\"addnews\" />\r\n");
      out.write("\t\t\t\t\t\t<button class=\"button bg-main icon-check-square-o\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t提交</button>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"index_newMsg.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button bg-main icon-check-square-o\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-left: 30px;\">取消</button>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"button bg-main icon-check-square-o\" type=\"reset\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-left: 30px;\">重置</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
