/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-27 09:05:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.DoPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.huatai.biz.BlackUserBiz;
import com.huatai.biz.impl.BlackUserBizImpl;
import com.huatai.entity.*;
import com.huatai.biz.impl.UserBizImpl;
import com.huatai.biz.UserBiz;
import com.huatai.biz.impl.MessageBizImpl;
import com.huatai.biz.MessageBiz;
import com.huatai.util.CommonUtils;
import java.util.*;
import java.sql.*;

public final class do_005faddnotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.huatai.entity");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.huatai.biz.BlackUserBiz");
    _jspx_imports_classes.add("com.huatai.biz.impl.MessageBizImpl");
    _jspx_imports_classes.add("com.huatai.biz.impl.UserBizImpl");
    _jspx_imports_classes.add("com.huatai.biz.MessageBiz");
    _jspx_imports_classes.add("com.huatai.util.CommonUtils");
    _jspx_imports_classes.add("com.huatai.biz.impl.BlackUserBizImpl");
    _jspx_imports_classes.add("com.huatai.biz.UserBiz");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	//验证用户登录信息
	//1.首先接收输入的信息,
	String msgaccount = request.getParameter("msgaccount");
	String msgpwd = request.getParameter("msgpwd");
	String msgtitle = request.getParameter("msgtitle");
	String msgcontent = request.getParameter("msgcontent");

	UserBiz userbiz = new UserBizImpl();
	UserInfo msguser = userbiz.findUser(msgaccount, msgpwd);

	//System.out.println("msguser" + msguser.getPassword());
	//2.将接收的数据与数据库进行比较,
	if (msguser == null) {
		//3.不相同则跳回原登录页面
		request.setAttribute("err", "账户信息不符合,请重新输入");
		request.getRequestDispatcher("../addnotice.jsp").forward(request, response);
	} else {
		//4.若用户名和密码正确,则需要验证是否进入黑名单;若没有进入则登录;进入则不允许登录,
		BlackUserBiz blackrusebiz = new BlackUserBizImpl();
		BlackUserInfo bu = blackrusebiz.isExitAccount(msguser.getUserid());
		if (bu != null) {
			if (msgaccount.equals(bu.getAccount())) {
				request.setAttribute("err", "权限受限，禁止登录。");
				request.getRequestDispatcher("../addnotice.jsp").forward(request, response);
			}
		} else {//可以登陆,并且将留言信息插入留言表中
			String msgid = CommonUtils.getUUid();
			String uid = msguser.getUserid();
			Message message = new Message(msgid, msgtitle, msgcontent, msgaccount, uid);
			MessageBiz massagebiz = new MessageBizImpl();
			boolean isSuccess = massagebiz.insertMessage(message);
			if (isSuccess) {
				request.setAttribute("err", "留言成功");
				request.getRequestDispatcher("../addnotice.jsp").forward(request, response);
			} else {
				request.setAttribute("err", "留言失败");
				request.getRequestDispatcher("../addnotice.jsp").forward(request, response);
			}
		}
	}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
