/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-21 08:45:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.DoPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.huatai.dao.BlackUserDao;
import com.huatai.entity.*;
import com.huatai.dao.impl.UserDaoImpl;
import com.huatai.dao.impl.BlackUserDaoImpl;
import com.huatai.dao.UserDao;
import java.util.*;
import java.sql.*;

public final class do_005findexlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.huatai.entity");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.huatai.dao.BlackUserDao");
    _jspx_imports_classes.add("com.huatai.dao.impl.BlackUserDaoImpl");
    _jspx_imports_classes.add("com.huatai.dao.impl.UserDaoImpl");
    _jspx_imports_classes.add("com.huatai.dao.UserDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	//验证企业用户和求职者的登录信息
	//1.首先接收输入的信息,
	String userName = request.getParameter("username");
	String password = request.getParameter("password");
	String useroot = request.getParameter("workor");

	int root = 2;//--1代表管理员；2代表企业用户；3代表求职者
	if ("企业用户".equals(useroot)) {
		root = 2;
	} else if ("求职用户".equals(useroot)) {
		root = 3;
	}
	UserDao userDao = new UserDaoImpl();
	UserInfo user = userDao.findUser(userName, password, root);

	//2.将接收的数据与数据库进行比较,
	if (user == null) {
		//3.不相同则跳回原登录页面index.jsp
		request.setAttribute("indexmsg", "账户信息不符合,请重新输入");
		request.getRequestDispatcher("../index.jsp").forward(request, response);

	} else {
		//4.若用户名和密码正确,则需要验证是否进入黑名单;若没有进入则登录;进入则不允许登录,
		BlackUserDao blackruse = new BlackUserDaoImpl();
		BlackUserInfo bu = blackruse.isExitAccount(user.getUserid());
		if (bu != null) {
			if (userName.equals(bu.getAccount())) {
				request.setAttribute("indexmsg", "权限受限，禁止登录。");
				request.getRequestDispatcher("../index.jsp").forward(request, response);
			} else {
				if (root == 2) {
					session.setAttribute("comuser", userName);
					response.sendRedirect("../Companylogin/comloginsuccess.jsp");
				} else if (root == 3) {
					session.setAttribute("workuser", userName);
					response.sendRedirect("../Worklogin/workloginsuccess.jsp");
				}
			}
		} else {
			if (root == 2) {
				session.setAttribute("comuser", userName);
				response.sendRedirect("../Companylogin/comloginsuccess.jsp");
			} else if (root == 3) {
				session.setAttribute("workuser", userName);
				response.sendRedirect("../Worklogin/workloginsuccess.jsp");
			}
		}

	}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
