/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-24 14:52:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Companylogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.huatai.biz.impl.CompanyBizImpl;
import com.huatai.util.CommonUtils;
import com.huatai.biz.CompanyBiz;
import com.huatai.entity.*;
import org.apache.commons.fileupload.*;
import org.apache.commons.fileupload.servlet.*;
import java.util.*;
import java.io.*;
import org.apache.commons.fileupload.disk.*;
import java.util.Date;
import java.util.*;

public final class do_005fUpdateInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.apache.commons.fileupload");
    _jspx_imports_packages.add("com.huatai.entity");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.apache.commons.fileupload.servlet");
    _jspx_imports_packages.add("org.apache.commons.fileupload.disk");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.huatai.util.CommonUtils");
    _jspx_imports_classes.add("com.huatai.biz.CompanyBiz");
    _jspx_imports_classes.add("com.huatai.biz.impl.CompanyBizImpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	//获得公司信息;
	String comuserid = request.getParameter("comid");
	//根据userid查询改简历是否已存在,来判断是否完善
	CompanyBiz combiz = new CompanyBizImpl();
	Company comp = combiz.isExit(comuserid);

	if (comp != null) {
		if (comuserid.equals(comp.getUsercomid())) {
			request.setAttribute("companymsg", "公司信息已经存在,无须完善");
			request.getRequestDispatcher("UpdateInfo.jsp").forward(request, response);
		}
	} else {
		//System.out.println("userid==" + userid);
		String compid = CommonUtils.getUUid();
		String comname = request.getParameter("comname");
		String comHrman = request.getParameter("comHrman");
		String comphone = request.getParameter("comphone");
		String comaddress = request.getParameter("comaddress");

		int kind = Integer.parseInt(request.getParameter("comkind"));
		String comkind = "";
		if (1 == kind) {
			comkind = "计算机/网络";
		} else if (2 == kind) {
			comkind = "广告/艺术";
		} else if (3 == kind) {
			comkind = "医疗/护理";
			//System.out.println("reslevel==" + level);
		} else if (4 == kind) {
			comkind = "旅游/酒店";
		} else if (5 == kind) {
			comkind = "仓储/物流";
		} else if (6 == kind) {
			comkind = "教育/培训";
		} else if (7 == kind) {
			comkind = "市场/媒介";
		} else if (8 == kind) {
			comkind = "娱乐/休闲";
		} else if (9 == kind) {
			comkind = "建筑";
		} else if (10 == kind) {
			comkind = "餐饮";
		}

		String cominterest = request.getParameter("cominterest");
		String comcontent = request.getParameter("comcontent");

		//System.out.println("resmoney=="+resmoney);
		Company company = new Company(compid, comname, comHrman, comphone, comaddress, comkind, cominterest,
				comcontent, comuserid);

		//添加公司
		CompanyBiz Ciz = new CompanyBizImpl();
		boolean isSuccess = Ciz.insertResume(company);
		if (isSuccess) {
			response.sendRedirect("LookInfo.jsp");
		} else {
			response.getWriter().println("<script type='text/javascript'>alert('公司信息完善失败！');</script>");
		}
	}

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
