/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-24 14:55:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Companylogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.huatai.biz.impl.JobBizImpl;
import com.huatai.util.CommonUtils;
import com.huatai.biz.JobBiz;
import com.huatai.biz.UserBiz;
import com.huatai.biz.impl.UserBizImpl;
import com.huatai.biz.CompanyBiz;
import com.huatai.biz.impl.CompanyBizImpl;
import com.huatai.entity.*;
import java.util.Date;
import java.util.*;

public final class do_005faddJob_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.huatai.entity");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.huatai.biz.impl.UserBizImpl");
    _jspx_imports_classes.add("com.huatai.biz.impl.JobBizImpl");
    _jspx_imports_classes.add("com.huatai.biz.JobBiz");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.huatai.util.CommonUtils");
    _jspx_imports_classes.add("com.huatai.biz.CompanyBiz");
    _jspx_imports_classes.add("com.huatai.biz.impl.CompanyBizImpl");
    _jspx_imports_classes.add("com.huatai.biz.UserBiz");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	//获得登录公司的id;
	String comuser = (String) request.getSession().getAttribute("comuser");
	//查询出登录用户的id,以便后面座位发布职位的外键
	UserBiz userbiz = new UserBizImpl();
	UserInfo userid = userbiz.getUserid(comuser);
	String comid = userid.getUserid();
	//获得登录Id之后，根据comid查询该公司是否已经有公司信息，若已经完善信息，则可以发布职位；若没有，则弹框提示完善信息，
	CompanyBiz companybiz = new CompanyBizImpl();
	Company comInfo = companybiz.isExit(comid);
	//boolean boo = comInfo == null;
	//System.out.println("comInfo!=null" + boo);
	if (comInfo != null) {
		//String comid = (String) request.getAttribute("compid");
		//获取提交的表单数据
		//System.out.println("userid==" + userid);
		String jobid = CommonUtils.getUUid();
		String jtitle = request.getParameter("jtitle");
		String jwork = request.getParameter("jwork");
		String jtime = request.getParameter("jtime");
		int kind = Integer.parseInt(request.getParameter("jkind"));
		String jkind = "";
		if (1 == kind) {
			jkind = "兼职";
		} else if (2 == kind) {
			jkind = "全职";
		}
		int level = Integer.parseInt(request.getParameter("jlevel"));
		String jlevel = "";
		if (1 == level) {
			jlevel = "初中";
		} else if (2 == level) {
			jlevel = "高中";
		} else if (3 == level) {
			jlevel = "本科";
		} else if (4 == level) {
			jlevel = "研究生";
		} else if (5 == level) {
			jlevel = "博士";
		}
		int money = Integer.parseInt(request.getParameter("jmoney"));
		String jmoney = "";
		if (1 == money) {
			jmoney = "2000以下";
		} else if (2 == money) {
			jmoney = "2000~4000";
		} else if (3 == money) {
			jmoney = "4000~6000";
		} else if (4 == money) {
			jmoney = "6000~8000";
		} else if (5 == money) {
			jmoney = "8000~10000";
		} else if (6 == money) {
			jmoney = "10K以上";
		}

		String jaddress = request.getParameter("jaddress");
		String jphone = request.getParameter("jphone");

		//System.out.println("resmoney=="+resmoney);
		Job job = new Job(jobid, jtitle, jwork, jtime, jkind, jlevel, jmoney, jaddress, jphone, comid);

		//添加公司
		JobBiz jobiz = new JobBizImpl();
		boolean isSuccess = jobiz.insertResume(job);
		if (isSuccess) {
			response.sendRedirect("LookEmpInfo.jsp");
		} else {
			response.getWriter().println("<script type='text/javascript'>alert('职位发布失败！');</script>");
		}
	} else {
		response.getWriter().println("<script type='text/javascript'>alert('公司信息未完善！');</script>");
	}

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
