/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2019-05-21 08:51:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.HrLoginPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- 浏览器兼容性设置-->\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- 视图兼容设置 -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<!-- 页面默认使用极速核 -->\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/Hrlogin/pintuer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/Hrlogin/admin.css\">\r\n");
      out.write("<script src=\"../js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".leftnav h2\").click(function() {\r\n");
      out.write("\t\t\t$(this).next().slideToggle(200).next(\"ul\").slideDown(200);\r\n");
      out.write("\t\t\t$(this).siblings().next(\"ul\").slideUp(200);\r\n");
      out.write("\t\t\t//$(this).toggleClass(\"on\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//导航栏信息的显示，点击左侧那个，就会显示在上方\r\n");
      out.write("\t\t$(\".leftnav ul li a\").click(function() {\r\n");
      out.write("\t\t\t$(\"#a_leader_txt\").text($(this).text());\r\n");
      out.write("\t\t\t$(\".leftnav ul li a\").removeClass(\"on\");\r\n");
      out.write("\t\t\t$(this).addClass(\"on\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f2f9fd;\">\r\n");
      out.write("\t<div class=\"header bg-main\">\r\n");
      out.write("\t\t<div class=\"logo margin-big-left fadein-top\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<img src=\"../images/y.jpg\" class=\"radius-circle rotate-hover\"\r\n");
      out.write("\t\t\t\t\theight=\"50\" alt=\"\" />后台管理中心\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"head-l\">\r\n");
      out.write("\t\t\t<a class=\"button button-little bg-blue\"> <span class=\"icon-login\"></span>\r\n");
      out.write("\t\t\t\t管理员：");
      out.print(request.getSession().getAttribute("admin"));
      out.write("\r\n");
      out.write("\t\t\t</a> &nbsp;&nbsp; <a class=\"button button-little bg-green\"\r\n");
      out.write("\t\t\t\thref=\"adminindex.jsp\"> <span class=\"icon-home\"></span> 后台首页\r\n");
      out.write("\t\t\t</a> &nbsp;&nbsp; <a class=\"button button-little bg-red\"\r\n");
      out.write("\t\t\t\thref=\"../HrLogin.jsp\" ");
session.setAttribute("Hrmsg", "");
      out.write("> <span\r\n");
      out.write("\t\t\t\tclass=\"icon-power-off\"></span> 退出登录\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"leftnav\">\r\n");
      out.write("\t\t<div class=\"leftnav-title\">\r\n");
      out.write("\t\t\t<strong><span class=\"icon-list\"></span>菜单列表</strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-user\"></span><a target=\"right\">&nbsp;&nbsp;基本设置</a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul style=\"display: block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 管理用户对应的表达便是黑名单表tb_black_info 1代表不能登录,0代表能登录 -->\r\n");
      out.write("\t\t\t<li><a href=\"basicSet/usermanage.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>管理用户</a></li>\r\n");
      out.write("\t\t\t<!-- 显示黑名单信息 -->\r\n");
      out.write("\t\t\t<li><a href=\"basicSet/blackuserinfo.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>黑名单表</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"basicSet/updatepwd.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>修改密码</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-pencil-square-o\"></span> <a\r\n");
      out.write("\t\t\t\thref=\"skill/skillMsg.jsp\" target=\"right\">求职技巧</a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"skill/skill_add.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>添加技巧</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"skill/do_skill_list.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>管理技巧</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-pencil-square-p\"></span><a\r\n");
      out.write("\t\t\t\thref=\"message/messageMsg.jsp\" target=\"right\">&nbsp;系统留言</a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<!-- \\f044 -->\r\n");
      out.write("\t\t\t<li><a href=\"message/do_message_list.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>留言管理</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-pencil-square-n\"></span><a href=\"new/newMsg.jsp\"\r\n");
      out.write("\t\t\t\ttarget=\"right\">&nbsp;新闻动态</a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"new/new_add.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>添加新闻</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"new/do_news_list.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>编辑新闻</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"new/topic_add.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>添加主题</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"new/do_topic_list.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>编辑主题</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-pencil-square-f\"></span><a\r\n");
      out.write("\t\t\t\thref=\"modelupload/modelMsg.jsp\" target=\"right\">&nbsp;文件上传</a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"modelupload/model_add.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>添加文件</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"modelupload/do_model_list.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>编辑文件</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<span class=\"icon-pencil-square-m\"></span>&nbsp;查看信息</a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"lookinfo/lookuser.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>个人信息</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"lookinfo/lookCompany.jsp\" target=\"right\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-caret-right\"></span>公司信息</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<ul class=\"bread\">\r\n");
      out.write("\t\t<li><a href=\"rightmessage.jsp\" target=\"right\" class=\"icon-home\">\r\n");
      out.write("\t\t\t\t首页</a></li>\r\n");
      out.write("\t\t<li><a href=\"##\" id=\"a_leader_txt\"></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div class=\"admin\">\r\n");
      out.write("\t\t<!-- 点击左侧菜单，便会显示在此处   rameborder=\"0\" -->\r\n");
      out.write("\t\t<iframe scrolling=\"auto\" src=\"rightmessage.jsp\" name=\"right\"\r\n");
      out.write("\t\t\twidth=\"100%\" height=\"100%\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"text-align: center;\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
